{% set name = "lttbc" %}
{% set version = "0.2.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lttbc-{{ version }}.tar.gz
  sha256: dff2539ecdd8ba1500c09be22ffd52fd5146f98c12dc7290b6b938a5b656b474

build:
  number: 2
  skip: true  # [py<36]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - numpy
    - pip
    - python
    - setuptools-scm
  run:
    - python

test:
  imports:
    - lttbc
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dgoeries/lttbc/
  summary: Largest triangle three buckets module for Python written in C
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
