{% set name = "lttbc" %}
{% set version = "0.2.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lttbc-{{ version }}.tar.gz
  sha256: 8ee634437b8a265d73de758bb81354aee4206698caa0e65fdd33568dc2373d47

build:
  number: 2
  skip: true  # [py<36]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - numpy
    - pip
    - python
    - setuptools-scm
  run:
    - {{ pin_compatible('numpy') }}
    - python

test:
  imports:
    - lttbc
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dgoeries/lttbc/
  summary: Largest triangle three buckets module for Python written in C
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
