{% set name = "lttbc" %}
{% set version = "0.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lttbc-{{ version }}.tar.gz
  sha256: eecffefddf8883091070cbde460011c5301c9291ab61b707c87260071588a897

build:
  number: 0
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy >=2.0                            # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - numpy >=2.0
    - pip
    - python
    - setuptools >=65.5.0
    - wheel >=0.40
  run:
    - python
    - numpy >=2.0

test:
  imports:
    - lttbc
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dgoeries/lttbc/
  summary: Largest triangle three buckets module for Python written in C
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
